documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**/*"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "pnpm-lock.yaml"
          - "packages/*/package.json"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.test.ts"
          - "**/*.spec.ts"
          - "**/test/**/*"
          - "**/tests/**/*"

typescript:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.ts"
          - "**/*.tsx"
          - "**/tsconfig.json"

satori-html:
  - changed-files:
      - any-glob-to-any-file:
          - "packages/satori-html/**/*"
